services:
  #Build Database Service#
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
    - ../.env
    ports:
    - "5332:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    networks:
    - forecast_net

  #FastAPI App#
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: forecast_app
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
    - "8000:8000"
    depends_on:
    - db
    env_file:
    - ../.env
    volumes:
    - ../src:/app/src
    - ../config:/app/config
    - ../data:/app/data
    - ../scripts:/app/scripts
    networks:
    - forecast_net

volumes:
  db_data:

networks:
  forecast_net:
    name: docker_forecast_net
    driver: bridge